In [62]:
import numpy as np

In [63]:
a = np.array([1,2,3,4,5])

In [64]:
print(a)

[1 2 3 4 5]


In [65]:
lst = [1,2,3,4,5,6]
print(np.array(lst))

[1 2 3 4 5 6]


In [66]:
print(type(a))

<class 'numpy.ndarray'>


In [67]:
lst1 = [1,2,3,4,5,6]
lst2 = [2,3,4,5,6,7]
lst3 = [3,4,5,6,7,8]

In [68]:
arr = np.array([lst1,lst2,lst3])
arr

array([[1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6, 7],
       [3, 4, 5, 6, 7, 8]])

In [69]:
arr.shape

(3, 6)

In [70]:
arr[:,0]

array([1, 2, 3])

In [71]:
arr[:,5]

array([6, 7, 8])

In [72]:
arr<3

array([[ True,  True, False, False, False, False],
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [73]:
import numpy as np

In [74]:
lst = [1,2,3,4,5]
arr = np.array(lst)
arr

array([1, 2, 3, 4, 5])

In [75]:
lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [3,4,5,6,7]
arr1 = np.array([lst1,lst2,lst3])

In [76]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [77]:
arr1.shape

(3, 5)

In [78]:
type(arr1)

numpy.ndarray

In [79]:
arr

array([1, 2, 3, 4, 5])

In [80]:
arr[2]

3

In [81]:
arr[:2]

array([1, 2])

In [82]:
arr[2:]

array([3, 4, 5])

In [83]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [84]:
arr1[:,1]

array([2, 3, 4])

In [85]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [86]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [87]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [88]:
arr1[0:,3:].shape

(3, 2)

In [89]:
arr1[0:,0]
arr1[0:,4]

array([5, 6, 7])

In [90]:
arr

array([1, 2, 3, 4, 5])

In [91]:
arr<2

array([ True, False, False, False, False])

In [92]:
arr[arr<2]

array([1])

In [93]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [94]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [95]:
    np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [96]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [97]:
np.random.random((2,2))

array([[0.67251024, 0.97007099],
       [0.98857911, 0.7781032 ]])

In [98]:
np.random.seed(121)
np.random.randint((10,50))

array([ 2, 21])

In [99]:
n1 = np.array([[10,20,30],[40,50,60]])

In [100]:
n1

array([[10, 20, 30],
       [40, 50, 60]])

In [101]:
np.sum(n1)

210

In [102]:
np.sum(n1,axis = 0)

array([50, 70, 90])

In [103]:
np.sum(n1,axis = 1)

array([ 60, 150])

In [104]:
import numpy as np

In [105]:
arr = np.array([1,2,3,3])

In [106]:
print(arr)

[1 2 3 3]


In [107]:
arr.ndim

1

In [108]:
arr.shape

(4,)

In [109]:
arr1 = np.array([[1,2,3],[3,4,5],[5,6,7]])

In [110]:
print(arr1)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [111]:
arr1.shape

(3, 3)

In [112]:
arr1.ndim

2

In [113]:
import numpy as np

In [114]:
np.random.seed(111)
a = np.random.randint(1,500,30).reshape(6,5)
a

array([[341, 365, 469, 213,  87],
       [276, 170, 323, 119, 467],
       [297, 456, 442,   8, 269],
       [267, 450, 369, 217, 285],
       [271, 419,  22,  55, 201],
       [ 38, 461, 231, 187, 269]])

In [115]:
a[2:5,3:]

array([[  8, 269],
       [217, 285],
       [ 55, 201]])

In [116]:
import numpy as np

In [117]:
np.random.seed(12)
arr = np.random.randint(1,100,15)
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50, 53,  6, 14, 90, 35])

In [118]:
import numpy as np
a = np.array([1,2,3,4]).reshape(2,2)
b = np.array([5,6,7,8]).reshape(2,2)

In [119]:
a

array([[1, 2],
       [3, 4]])

In [120]:
b

array([[5, 6],
       [7, 8]])

In [121]:
a + b

array([[ 6,  8],
       [10, 12]])

In [122]:
# Exercise

In [123]:
import numpy as np

In [124]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [125]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
arr1 = np.random.randint(10,100,10)

In [127]:
arr1

array([85, 84, 10, 86, 23, 92, 99, 45, 72, 45])

In [128]:
arr3 = np.arange(10,21)

In [129]:
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [130]:
arr4 = np.array([5] * 10) 

In [131]:
arr4

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [132]:
arr5 = np.random.randint(1,20,9)

In [133]:
arr5

array([ 2,  1, 19, 19, 17,  7, 14, 10, 14])

In [134]:
arr6 = arr5.reshape(3,3)

In [135]:
arr6

array([[ 2,  1, 19],
       [19, 17,  7],
       [14, 10, 14]])

In [136]:
arr7 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
arr7 [arr7%2==0] = 0

In [137]:
arr7

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0, 17,
        0, 19,  0])

In [138]:
arr8 = np.linspace(0,1,9).reshape(3,3)

In [139]:
arr8

array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

In [140]:
arr9 = np.arange(1,17).reshape(4,4)

In [141]:
arr9

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [142]:
arr10 = arr9[1:,1:3]

In [143]:
arr10

array([[ 6,  7],
       [10, 11],
       [14, 15]])

In [144]:
a = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
b = np.array([9,8,7,6,5,4,3,2,1]).reshape(3,3)

In [145]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [146]:
b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [147]:
arr11 = np.hstack((a,b))

In [148]:
arr11

array([[1, 2, 3, 9, 8, 7],
       [4, 5, 6, 6, 5, 4],
       [7, 8, 9, 3, 2, 1]])

In [149]:
arr12 = np.vstack((a,b))

In [150]:
arr12

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

## PRATICE - 29.08.2022

In [151]:
# Practice ==>

In [152]:
import numpy as np 

In [153]:
#  creating 1 dimensional array with the help of list 
myarr = [1,2,3,4,5,6]
arr = np.array(myarr)
# myarr
arr

array([1, 2, 3, 4, 5, 6])

In [154]:
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [155]:
myarr = np.array([1,2,3,4,5,6,7,8,9,10])
myarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [156]:
import numpy as np

In [157]:
# creating 1 dimensional array with the help of user input
nums = []
ran = int(input('Enter a range here :'))
for i in range(ran):
    inpu = int(input('Enter number to enter here :'))
    nums.append(inpu)

print(nums) 
arr1 = np.array(nums)
print(arr1) 
print(type(nums))
print(type(arr1))  

: 

In [ ]:
# creating 2 dimensional array with the help of list 
# show dimensional of the array 
arr2 = [[1,2,3],[4,5,6],[7,8,9]]
myarr = np.array(arr2)
print(myarr)
print('dimension of the array is : ',myarr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimension of the array is :  2


In [ ]:
# creating 2 dimensional array with the help of direct input in the form of list 
# show shape of the array and class type  
arr3 = np.array([[7,8,9],[4,5,6],[1,2,3]])
print(arr3)
print('Shape of the array is : ',arr3.shape)
print(type(arr3))

[[7 8 9]
 [4 5 6]
 [1 2 3]]
Shape of the array is :  (3, 3)
<class 'numpy.ndarray'>


In [ ]:
# Ceating 2 dimensional array with the help of user input

matrix = []
row = int(input('Enter number of rows here :'))
colm = int(input('ENter number of columns here :'))
for i in range(row):
    data = []
    for j in range(colm):
        value = int(input('Enter value here :'))
        data.append(value)
    matrix.append(data)
for i in range(row):
    for j in range(colm):
        print(matrix[i][j],end = ' ')
    print()
    # print(type(matrix))



1 2 3 
4 5 6 
7 8 9 


In [ ]:
# creating 2 dimensional array with the help of user input

import numpy as np

matrix = []
row = int(input('Enter number of rows here : '))
colm = int(input('Enter number of colm here :'))
for i in range(row):
    data = []
    for j in range(colm):
        value = int(input('Enter value here :'))
        data.append(value)
    matrix.append(data)
    arr4 = np.array(matrix)
for r in range(row):
    for j in range(colm):
        print(arr4[r][j],end = ' ')
    print()
    print(type(arr4))

5 6 
<class 'numpy.ndarray'>
8 1 
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

matrix1 = []
rang = int(input('Enetr Range number here :'))
for i in range(rang):
    inpu = int(input('Enter numbers here : '))
    matrix1.append(inpu)
arr4 = np.array(matrix1)
print(arr4)
arr4[:3]


[4 5 6 9]


array([4, 5, 6])

In [ ]:
import numpy as np

In [ ]:
np.random.seed(12)
arr5 = np.random.randint(1,100,15)
print(arr5)

[76 28  7  3  4 68 77 49 23 50 53  6 14 90 35]


In [ ]:
import numpy as np
np.random.seed(2)
arr6 = np.random.randint(1,100,10)
print(arr6)

[41 16 73 23 44 83 76  8 35 50]


In [ ]:
import numpy as np
a = np.array([[10,20,30],[30,40,50],[60,70,80]])
print(a)
print(type(a))
print(a.size)
print(a.shape)

[[10 20 30]
 [30 40 50]
 [60 70 80]]
<class 'numpy.ndarray'>
9
(3, 3)


In [ ]:
print(a[:2])

[[10 20 30]
 [30 40 50]]


In [ ]:
arr6 = np.array([[1,2,3],
[4,5,6],
[7,8,9]
])

In [ ]:
print(arr6)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(type(arr6))
print(arr6[1,0:3])
print(arr6[0:2,0:2])
print(arr6.size)
print(arr6.shape)

<class 'numpy.ndarray'>
[4 5 6]
[[1 2]
 [4 5]]
9
(3, 3)


In [ ]:
import numpy as np
np.random.seed(11)
arr7 = np.random.randint(1,500,30).reshape(6,5)
print(arr7)

[[410 192  81  92 338]
 [440 270 333 162  72]
 [339 281 110  93 177]
 [254 417 302 237 126]
 [389  35 141 386 331]
 [ 38 232 469  82  92]]


In [ ]:
arr7[2,3]

93

In [ ]:
nil = arr7[3:5,2:4]
print(nil)

[[302 237]
 [141 386]]


In [ ]:
arr7

array([[410, 192,  81,  92, 338],
       [440, 270, 333, 162,  72],
       [339, 281, 110,  93, 177],
       [254, 417, 302, 237, 126],
       [389,  35, 141, 386, 331],
       [ 38, 232, 469,  82,  92]])

In [ ]:
arr7[5,2]

469

In [ ]:
arr7[2]

array([339, 281, 110,  93, 177])

In [ ]:
arr7[0:,3]

array([ 92, 162,  93, 237, 386,  82])

In [ ]:
arr7

array([[410, 192,  81,  92, 338],
       [440, 270, 333, 162,  72],
       [339, 281, 110,  93, 177],
       [254, 417, 302, 237, 126],
       [389,  35, 141, 386, 331],
       [ 38, 232, 469,  82,  92]])

In [ ]:
a=5
b=6
c=a+b
print('a+b = ',c)

a+b =  11


In [ ]:
print('hi i am nilesh')

hi i am nilesh


In [ ]:
# Code for ATM
total = 1500
withdrawl = int(input('Enter your value here :'))
if withdrawl > total:
    print('Insufficient amount')
else:
    remaining = total - withdrawl
    print('Thank you for visiting nileshs ATM')
    print('Your transaction is succesfull your remaining amount is ',remaining)    

Thank you for visiting nileshs ATM
Your transaction is succesfull your remaining amount is  1300


In [61]:
print(2+2)

4


In [1]:
print(4**4)

256


In [2]:
print(5/2)

2.5


In [3]:
print(5//2)

2


In [4]:
print(5%1)

0


In [5]:
print(1%5)

1


In [7]:
# Use of different operators in numpy array
import numpy as np

arr8 = np.arange(1,5)

In [8]:
arr8

array([1, 2, 3, 4])

In [11]:
import numpy as np 

arr9 = np.arange(5,9)

In [12]:
arr9

array([5, 6, 7, 8])

In [13]:
arr8 + arr9

array([ 6,  8, 10, 12])

In [14]:
arr9 - arr8

array([4, 4, 4, 4])

In [15]:
arr8 * arr9

array([ 5, 12, 21, 32])

In [16]:
arr8 ** arr9

array([    1,    64,  2187, 65536])

In [17]:
arr8 / arr9

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [18]:
import numpy as np 
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])


In [19]:
a+b 

array([ 6,  8, 10, 12])

In [20]:
a-b

array([-4, -4, -4, -4])

In [21]:
a*b

array([ 5, 12, 21, 32])

In [22]:
a**b

array([    1,    64,  2187, 65536])

In [24]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [25]:
a//b

array([0, 0, 0, 0])

In [26]:
# Use of conditional statements in numpy array
import numpy as np
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
print(a>10)

[False False False False False False False False False False  True  True
  True  True  True]


In [28]:
print(a<5)

[ True  True  True  True False False False False False False False False
 False False False]


In [29]:
print(a%2==0)

[False  True False  True False  True False  True False  True False  True
 False  True False]


In [30]:
# to find even value in an array

a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [31]:
#  Assigning value after applying a condition on numpy array
a[a %2 == 0] = 0
a

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15])

In [33]:
import numpy as np
a = np.zeros(5)
a


array([0., 0., 0., 0., 0.])

In [35]:
b = np.zeros((5,2))
b

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

## Different functions in numpy , we can use all functions into one dimensional array  as well as  into two dimensional array 
## to work in a certain column or row , we have to use axis method
## axis = 0 ..........it denotes to column
## axis = 1 ..........it denotes to row

In [2]:
# One dimensional array with .zeros() function
import numpy as np
arr = np.zeros(5)              #it will create one dimensional array with zeros only
arr

array([0., 0., 0., 0., 0.])

In [4]:
# Two dimensional array with .zeros() function
import numpy as np
arr1 = np.zeros((2,3))         # if we want to create two dimensional array we have to give its size in tuple format 
arr1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# One dimensional array with .ones()functuion 
import numpy as np
arr2 = np.ones(5)            #it will create one dimensional array with ones only
arr2

array([1., 1., 1., 1., 1.])

In [7]:
# two dimensional array with .ones()functuion
import numpy as np 
arr3 = np.ones((5,5))          # if we want to create two dimensional array we have to give its size in tuple format 
arr3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# one dimensional array with .eye()functuion
import numpy as np
arr4 = np.eye(5)      # it will create two dimensional array with 1 filled in diagonal and rest is zero 
arr4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
# two dimensional array with .diag()functuion
import numpy as np
arr5 = np.diag((5,3,15,4))          #it will create two dimensional array and place given values to the functiona in a diagonal format and rest in zero 
arr5

np.diag(arr5)            #we can also find diagonal values present in an array by using diag function in this format

array([ 5,  3, 15,  4])

In [21]:
# np.random.randint() function
import numpy as np
arr6 = np.random.randint(1,10,3)      # it will create one dimensional array and take values between 1 to 9 , it will always gives 3 new random values 
arr6

array([2, 9, 8])

In [37]:
# np.random.seed( any value)
import numpy as np
np.random.seed(12)
arr11 = np.random.randint(1,15,10)       # by applying seed function we can freeze random values so we can et same result everytime
arr11

array([12, 12,  7, 14,  2,  3,  4,  4, 13,  1])

In [25]:
# np.random.randn() function
import numpy as np
arr7 = np.random.randn(2,2)  #it will create an two dimensional array by taking values from o to 1  it can also take negitive values
arr7

array([[ 1.51097974, -0.28448213],
       [-0.46600623, -0.02206956]])

In [28]:
# np.random.rand() function
arr8 = np.random.rand(5)          #it will create an one or two dimensional array by taking values closer to zero  

In [30]:
# max function
arr8 = np.array([1,4,3,5,7,9,1,3,5])
arr8
np.max(arr8) # it will show maximum value present in an array

9

In [31]:
# min function
arr8 = np.array([1,4,3,5,7,9,1,3,5])
arr8
np.min(arr8) # it will show minimum value present in an array

1

In [34]:
# squrt function
arr9 = np.sqrt(arr8)
arr9            # it will give square root of all numbers present in an array

array([1.        , 2.        , 1.73205081, 2.23606798, 2.64575131,
       3.        , 1.        , 1.73205081, 2.23606798])

In [36]:
# linspace function
import numpy as np
arr10 = np.linspace(1,2,5)          #it will give 5 values between 1 and 2 but by providing exact space between them , difference between all values is exactly same 
arr10

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

## Stacking in python, it can take multiple arrays and stack it horizontally and vertically thats why we have to give values inside a tuple 
## np.hstack((array1,array2)) .........it will stack two arrays horizontaly
## np.vstack((array1,array2)) .........it will stack two arrays vertically

In [38]:
import numpy as np
a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)


In [39]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [42]:
# Horizontal stacking
np.hstack((a,b))    # horizontal stack arrange two matrix in horizontally side by side  a b 

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [44]:
# Vertical stacking
np.vstack((a,b))      # vertical stack arrange two matrix in vertically up and down  a
                                                                                    #b 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

## Problems of numpy array  

In [45]:
# import numpy 
import numpy as np

In [46]:
# create an array
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [47]:
#create an array with 10 random integers
np.random.randint(1,50,10)

array([23,  6, 14, 26, 35, 12, 11,  1, 41, 13])

In [48]:
#  create an array from 10 to 20
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [49]:
# creatte an array which containg 5 ten times
np.array([5]*10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [51]:
# create one dimensional array then convert it into 3x3 matrix
import numpy as np
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
# create an array then convert all even to zero
import numpy as np
arr1 = np.arange(1,10)
print(arr1)
arr1[arr1%2==0] = 0
arr1

[1 2 3 4 5 6 7 8 9]


array([1, 0, 3, 0, 5, 0, 7, 0, 9])

In [56]:
# create a 2d array but all values should be in 0 and 1
import numpy as np
np.random.rand(3,3)


array([[0.94422514, 0.85273554, 0.00225923],
       [0.52122603, 0.55203763, 0.48537741],
       [0.76813415, 0.16071675, 0.76456045]])

In [58]:
# perform slicing
import numpy as np
arr3 = np.arange(1,17).reshape(4,4)
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [60]:
arr3[1:,1:3]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

In [63]:
# concatenate two array horizontally and vertically
import numpy as np
np.random.seed(10)
a = np.random.randint(1,50,9).reshape(3,3)
b = np.random.randint(11,100,9).reshape(3,3)

In [66]:
a

array([[10, 37, 16],
       [ 1, 29, 26],
       [30, 49, 30]])

In [67]:
b

array([[19, 84, 11],
       [51, 47, 27],
       [22, 65, 99]])

In [69]:
# hstack
np.hstack((a,b))

array([[10, 37, 16, 19, 84, 11],
       [ 1, 29, 26, 51, 47, 27],
       [30, 49, 30, 22, 65, 99]])

In [70]:
# vstack
np.stack((a,b))

array([[[10, 37, 16],
        [ 1, 29, 26],
        [30, 49, 30]],

       [[19, 84, 11],
        [51, 47, 27],
        [22, 65, 99]]])