In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:
df1 = pd.DataFrame(data = np.arange(0,20).reshape(5,4),index = ["Row1","Row2","Row3","Row4","Row5"],columns = ["Column1","Column2","Column3","Column4"])
df1

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [7]:
df = pd.DataFrame(data = np.arange(0,10).reshape(2,5),index = ["Row1","Row2"],columns = ["Column1","Column2","COlumn3","Column4","Column5"])

In [8]:
df

Column1  Column2  COlumn3  Column4  Column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9

In [9]:
df.head

<bound method NDFrame.head of       Column1  Column2  COlumn3  Column4  Column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9>

In [15]:
df.head()

Column1  Column2  COlumn3  Column4  Column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9

In [14]:
df1.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [20]:
df1.iloc[0 : , 0]

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int32

In [22]:
 df1.loc["Row5"]

Column1    16
Column2    17
Column3    18
Column4    19
Name: Row5, dtype: int32

In [23]:
df1

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [24]:
df1.iloc[0:,3]

Row1     3
Row2     7
Row3    11
Row4    15
Row5    19
Name: Column4, dtype: int32

In [1]:
pip install io

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement io (from versions: none)
ERROR: No matching distribution found for io
You should consider upgrading via the 'c:\Users\Lalit Gajanan Humane\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [2]:
from io import StringIO

In [3]:
import pandas as pd

In [4]:
data = ('col1,col2,col3\n'
        'x,y,1\n'
        'a,b,3\n'
        'a,s,d')

In [5]:
pd.read_csv(StringIO(data))

col1 col2 col3
0    x    y    1
1    a    b    3
2    a    s    d

In [9]:
df = pd.read_csv('Bowling_ODI.csv')
df

key        Player_Name  Country Playing_span  starting_year  \
0        1     M Muralitharan     Asia    1993-2011           1993   
1        2        Wasim Akram      PAK    1984-2003           1984   
2        3       Waqar Younis      PAK    1989-2003           1989   
3        4         WPUJC Vaas     Asia    1994-2008           1994   
4        5      Shahid Afridi     Asia    1996-2015           1996   
...    ...                 ...     ...          ...            ...   
2577  2578         TJ Zoehrer      AUS    1986-1994           1986   
2578  2579            K Zondo       SA    2018-2018           2018   
2579  2580        B Zuiderent       NL    1996-2011           1996   
2580  2581         Zulqarnain     PAK)    1985-1989           1985   
2581  2582  Zulqarnain Haider      PAK    2010-2010           2010   

      ending_year  Duration_in_year  Matches  Innings  Balls   Runs  Wickets  \
0            2011                18      350      341  18811  12326      534   
1            2003                19      356      351  18186  11812      502   
2            2003                14      262      258  12698   9919      416   
3            2008                14      322      320  15775  11014      400   
4            2015                19      398      372  17670  13632      395   
...           ...               ...      ...      ...    ...    ...      ...   
2577         1994                 8       22        0      0      0        0   
2578         2018                 0        5        0      0      0        0   
2579         2011                15       57        0      0      0        0   
2580         1989                 4       16        0      0      0        0   
2581         2010                 0        4        0      0      0        0   

         BBI month  Average  Econ    SR  
0     Jul-30   Jul    23.08  3.93  35.2  
1     May-15   May    23.52  3.89  36.2  
2     Jul-36   Jul    23.84  4.68  30.5  
3     Aug-19   Aug    27.53  4.18  39.4  
4     07-Dec   Dec    34.51  4.62  44.7  
...      ...   ...      ...   ...   ...  
2577       0     0     0.00  0.00   0.0  
2578       0     0     0.00  0.00   0.0  
2579       0     0     0.00  0.00   0.0  
2580       0     0     0.00  0.00   0.0  
2581       0     0     0.00  0.00   0.0  

[2582 rows x 17 columns]

In [11]:
df.head()

key     Player_Name  Country Playing_span  starting_year  ending_year  \
0    1  M Muralitharan     Asia    1993-2011           1993         2011   
1    2     Wasim Akram      PAK    1984-2003           1984         2003   
2    3    Waqar Younis      PAK    1989-2003           1989         2003   
3    4      WPUJC Vaas     Asia    1994-2008           1994         2008   
4    5   Shahid Afridi     Asia    1996-2015           1996         2015   

   Duration_in_year  Matches  Innings  Balls   Runs  Wickets     BBI month  \
0                18      350      341  18811  12326      534  Jul-30   Jul   
1                19      356      351  18186  11812      502  May-15   May   
2                14      262      258  12698   9919      416  Jul-36   Jul   
3                14      322      320  15775  11014      400  Aug-19   Aug   
4                19      398      372  17670  13632      395  07-Dec   Dec   

   Average  Econ    SR  
0    23.08  3.93  35.2  
1    23.52  3.89  36.2  
2    23.84  4.68  30.5  
3    27.53  4.18  39.4  
4    34.51  4.62  44.7

In [12]:
df.tail()

key        Player_Name  Country Playing_span  starting_year  \
2577  2578         TJ Zoehrer      AUS    1986-1994           1986   
2578  2579            K Zondo       SA    2018-2018           2018   
2579  2580        B Zuiderent       NL    1996-2011           1996   
2580  2581         Zulqarnain     PAK)    1985-1989           1985   
2581  2582  Zulqarnain Haider      PAK    2010-2010           2010   

      ending_year  Duration_in_year  Matches  Innings  Balls  Runs  Wickets  \
2577         1994                 8       22        0      0     0        0   
2578         2018                 0        5        0      0     0        0   
2579         2011                15       57        0      0     0        0   
2580         1989                 4       16        0      0     0        0   
2581         2010                 0        4        0      0     0        0   

     BBI month  Average  Econ   SR  
2577   0     0      0.0   0.0  0.0  
2578   0     0      0.0   0.0  0.0  
2579   0     0      0.0   0.0  0.0  
2580   0     0      0.0   0.0  0.0  
2581   0     0      0.0   0.0  0.0

In [20]:
df1 = pd.read_csv('Bowling_ODI.csv',usecols=["Matches","Runs"])
df1

Matches   Runs
0         350  12326
1         356  11812
2         262   9919
3         322  11014
4         398  13632
...       ...    ...
2577       22      0
2578        5      0
2579       57      0
2580       16      0
2581        4      0

[2582 rows x 2 columns]

In [22]:
df1.to_csv("Test.csv")

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [8]:
a = np.arange(0,20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [9]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [14]:
df = pd.DataFrame(a,index = [
    "row1","row2","row3","row4","row5"],
    columns = ["column1","column2","column3","column4"]
)

In [15]:
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [16]:
df.tail()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [17]:
type(df)

pandas.core.frame.DataFrame

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  5 non-null      int32
 1   column2  5 non-null      int32
 2   column3  5 non-null      int32
 3   column4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [19]:
 df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [24]:
a = df["column2" ]
a
type(a)

pandas.core.series.Series

In [21]:
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [22]:
df[['column1','column2','column4']]

column1  column2  column4
row1        0        1        3
row2        4        5        7
row3        8        9       11
row4       12       13       15
row5       16       17       19

In [26]:
 df.loc['row3']

column1     8
column2     9
column3    10
column4    11
Name: row3, dtype: int32

In [30]:
df.loc[['row1','row3']]

column1  column2  column3  column4
row1        0        1        2        3
row3        8        9       10       11

In [31]:
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [32]:
df.iloc[2:4,0:2]

column1  column2
row3        8        9
row4       12       13

In [33]:
df.iloc[0:4,1]

row1     1
row2     5
row3     9
row4    13
Name: column2, dtype: int32

In [34]:
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [35]:
df.iloc[0:,0]

row1     0
row2     4
row3     8
row4    12
row5    16
Name: column1, dtype: int32

In [36]:
df.iloc[0:,3]

row1     3
row2     7
row3    11
row4    15
row5    19
Name: column4, dtype: int32

In [1]:
import pandas as pd
import numpy as np

In [2]:
sample_data = np.arange(0,20).reshape(4,5)

In [3]:
print(sample_data)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [4]:
df = pd.DataFrame(data = np.arange(0,20).reshape(4,5),index = ['Row1','Row2','Row3','Row4'],columns = ['Column1','Column2','Column3','Column4','Column5'])

In [5]:
print(df)

      Column1  Column2  Column3  Column4  Column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19


In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Row1 to Row4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  4 non-null      int32
 1   Column2  4 non-null      int32
 2   Column3  4 non-null      int32
 3   Column4  4 non-null      int32
 4   Column5  4 non-null      int32
dtypes: int32(5)
memory usage: 112.0+ bytes


In [8]:
df.head()

Column1  Column2  Column3  Column4  Column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19

In [9]:
df.tail()

Column1  Column2  Column3  Column4  Column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19

In [10]:
type(df)

pandas.core.frame.DataFrame

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Row1 to Row4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  4 non-null      int32
 1   Column2  4 non-null      int32
 2   Column3  4 non-null      int32
 3   Column4  4 non-null      int32
 4   Column5  4 non-null      int32
dtypes: int32(5)
memory usage: 112.0+ bytes


In [12]:
df.describe()

Column1    Column2    Column3    Column4    Column5
count   4.000000   4.000000   4.000000   4.000000   4.000000
mean    7.500000   8.500000   9.500000  10.500000  11.500000
std     6.454972   6.454972   6.454972   6.454972   6.454972
min     0.000000   1.000000   2.000000   3.000000   4.000000
25%     3.750000   4.750000   5.750000   6.750000   7.750000
50%     7.500000   8.500000   9.500000  10.500000  11.500000
75%    11.250000  12.250000  13.250000  14.250000  15.250000
max    15.000000  16.000000  17.000000  18.000000  19.000000

In [13]:
# # Indexing

In [14]:
df.head()

Column1  Column2  Column3  Column4  Column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19

In [15]:
df.iloc[0:,0]

Row1     0
Row2     5
Row3    10
Row4    15
Name: Column1, dtype: int32

In [17]:
df.iloc[0:,4:].values


array([[ 4],
       [ 9],
       [14],
       [19]])

In [18]:
df.head()

Column1  Column2  Column3  Column4  Column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19

In [20]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
Column5    0
dtype: int64

In [21]:
import pandas as pd
from io import StringIO

In [22]:
 df = pd.read_csv('Bowling_ODI.csv')

In [23]:
df

key        Player_Name  Country Playing_span  starting_year  \
0        1     M Muralitharan     Asia    1993-2011           1993   
1        2        Wasim Akram      PAK    1984-2003           1984   
2        3       Waqar Younis      PAK    1989-2003           1989   
3        4         WPUJC Vaas     Asia    1994-2008           1994   
4        5      Shahid Afridi     Asia    1996-2015           1996   
...    ...                 ...     ...          ...            ...   
2577  2578         TJ Zoehrer      AUS    1986-1994           1986   
2578  2579            K Zondo       SA    2018-2018           2018   
2579  2580        B Zuiderent       NL    1996-2011           1996   
2580  2581         Zulqarnain     PAK)    1985-1989           1985   
2581  2582  Zulqarnain Haider      PAK    2010-2010           2010   

      ending_year  Duration_in_year  Matches  Innings  Balls   Runs  Wickets  \
0            2011                18      350      341  18811  12326      534   
1            2003                19      356      351  18186  11812      502   
2            2003                14      262      258  12698   9919      416   
3            2008                14      322      320  15775  11014      400   
4            2015                19      398      372  17670  13632      395   
...           ...               ...      ...      ...    ...    ...      ...   
2577         1994                 8       22        0      0      0        0   
2578         2018                 0        5        0      0      0        0   
2579         2011                15       57        0      0      0        0   
2580         1989                 4       16        0      0      0        0   
2581         2010                 0        4        0      0      0        0   

         BBI month  Average  Econ    SR  
0     Jul-30   Jul    23.08  3.93  35.2  
1     May-15   May    23.52  3.89  36.2  
2     Jul-36   Jul    23.84  4.68  30.5  
3     Aug-19   Aug    27.53  4.18  39.4  
4     07-Dec   Dec    34.51  4.62  44.7  
...      ...   ...      ...   ...   ...  
2577       0     0     0.00  0.00   0.0  
2578       0     0     0.00  0.00   0.0  
2579       0     0     0.00  0.00   0.0  
2580       0     0     0.00  0.00   0.0  
2581       0     0     0.00  0.00   0.0  

[2582 rows x 17 columns]

In [24]:
df.head()

key     Player_Name  Country Playing_span  starting_year  ending_year  \
0    1  M Muralitharan     Asia    1993-2011           1993         2011   
1    2     Wasim Akram      PAK    1984-2003           1984         2003   
2    3    Waqar Younis      PAK    1989-2003           1989         2003   
3    4      WPUJC Vaas     Asia    1994-2008           1994         2008   
4    5   Shahid Afridi     Asia    1996-2015           1996         2015   

   Duration_in_year  Matches  Innings  Balls   Runs  Wickets     BBI month  \
0                18      350      341  18811  12326      534  Jul-30   Jul   
1                19      356      351  18186  11812      502  May-15   May   
2                14      262      258  12698   9919      416  Jul-36   Jul   
3                14      322      320  15775  11014      400  Aug-19   Aug   
4                19      398      372  17670  13632      395  07-Dec   Dec   

   Average  Econ    SR  
0    23.08  3.93  35.2  
1    23.52  3.89  36.2  
2    23.84  4.68  30.5  
3    27.53  4.18  39.4  
4    34.51  4.62  44.7

In [25]:
data = ('colm1,colm2,col3\n'
'x,y,1\n'
'a,b,2\n'
'a,s,3')

In [26]:
type(data)

str

In [27]:
StringIO(data)

In [28]:
df = pd.DataFrame(StringIO(data))

In [29]:
df

0
0  colm1,colm2,col3\n
1             x,y,1\n
2             a,b,2\n
3               a,s,3

In [30]:
pd.read_csv(StringIO(data))

colm1 colm2  col3
0     x     y     1
1     a     b     2
2     a     s     3

In [37]:
 df = pd.read_csv('Bowling_ODI.csv',usecols = ['Wickets'])

In [38]:
df

Wickets
0         534
1         502
2         416
3         400
4         395
...       ...
2577        0
2578        0
2579        0
2580        0
2581        0

[2582 rows x 1 columns]

In [39]:
df.head()

Wickets
0      534
1      502
2      416
3      400
4      395