In [1]:
'''
What is PIP ?
PIP stands for Preferred installer program. We use pip to install different Python packages. 
Package is a Python module that can contain one or more modules or other packages. 
A module or modules that we can install to our application is a package. 
In programming, we do not have to write every utility program, instead we install packages and import them to our applications.

Installing packages using pip
Let us try to install numpy, called numeric python. It is one of the most popular packages in machine learning and data science community.

NumPy is the fundamental package for scientific computing with Python. It contains among other things:
1) a powerful N-dimensional array object
2) sophisticated (broadcasting) functions
3) tools for integrating C/C++ and Fortran code
4) useful linear algebra, Fourier transform, and random number capabilities


'''



'\nWhat is PIP ?\nPIP stands for Preferred installer program. We use pip to install different Python packages. \nPackage is a Python module that can contain one or more modules or other packages. \nA module or modules that we can install to our application is a package. \nIn programming, we do not have to write every utility program, instead we install packages and import them to our applications.\n\nInstalling packages using pip\nLet us try to install numpy, called numeric python. It is one of the most popular packages in machine learning and data science community.\n\nNumPy is the fundamental package for scientific computing with Python. It contains among other things:\n1) a powerful N-dimensional array object\n2) sophisticated (broadcasting) functions\n3) tools for integrating C/C++ and Fortran code\n4) useful linear algebra, Fourier transform, and random number capabilities\n\n\n'

In [ ]:
#   I have already installed numpy module so i am not reinstalling this module
#  but for installing any module we have to mention syntax in this format 
#  pip install module name into terminal shell or command prompt(cmd) 




In [2]:
import numpy as np
arr = [1,2,3,4,5,6,7,8,9]
np_lst = np.array(arr)
print(np_lst)

[1 2 3 4 5 6 7 8 9]


In [3]:
# Pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language. 
# i have already installed the big brother of numpy, pandas:

In [7]:
import pandas as pd
import numpy as np

arr = np.arange(1,11).reshape(2,5)  # numpy built in function arange which gives range between 1 to 10 because 11 in incluive ( in range end number is always inclusive )
dataframe = pd.DataFrame(arr)       # making a dta frame with the help of bulit in function of pandas      
print(dataframe)
print(arr)

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
# Let us import a web browser module, which can help us to open any website. We do not need to install this module, it is already installed by default with Python 3. 
# For instance if you like to open any number of websites at any time or if you like to schedule something, this webbrowser module can be used.

In [9]:
import webbrowser # web browser module to open websites

# list of urls: python
url_lists = [
    'http://www.python.org',
    'https://www.linkedin.com/in/asabeneh/',
    'https://github.com/Asabeneh',
    'https://twitter.com/Asabeneh',
]

# opens the above list of websites in a different tab
for url in url_lists:
    webbrowser.open_new_tab(url)

In [10]:
pip list  # to view whole module list installed into our system

Package                       Version
----------------------------- --------------------
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
anaconda-client               1.9.0
anaconda-navigator            2.1.4
anaconda-project              0.10.2
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
astroid                       2.6.6
astropy                       5.0.4
asttokens                     2.0.5
async-timeout                 4.0.1
atomicwrites                  1.4.0
attrs                         21.4.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
bea

In [11]:
pip show numpy # to show inforation of any package 

Name: numpy
Version: 1.21.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: c:\users\lalit gajanan humane\anaconda3\lib\site-packages
Requires: 
Required-by: xarray, tifffile, tables, statsmodels, seaborn, scipy, scikit-learn, scikit-image, PyWavelets, pyerfa, patsy, pandas, numexpr, numba, mkl-random, mkl-fft, matplotlib, imageio, imagecodecs, hvplot, holoviews, h5py, gensim, datashape, datashader, daal4py, Bottleneck, bokeh, bkcharts, astropy
Note: you may need to restart the kernel to use updated packages.


# Reading from URL

In [12]:

# By now you are familiar with how to read or write on a file located on you local machine. 
# Sometimes, we would like to read from a website using url or from an API. 
# API stands for Application Program Interface. 
# It is a means to exchange structured data between servers primarily as json data. 
# To open a network connection, we need a package called requests - 
# it allows to open a network connection and to implement CRUD(create, read, update and delete) operations. 
# In this section, we will cover only reading ore getting part of a CRUD.

# We will see get, status_code, headers, text and json methods in requests module:

In [ ]:


# get(): to open a network and fetch data from url - it returns a response object
# status_code: After we fetched data, we can check the status of the operation (success, error, etc)
# headers: To check the header types
# text: to extract the text from the fetched response object
# json: to extract json data Let's read a txt file from this website, https://www.w3.org/TR/PNG/iso_8859-1.txt.

In [13]:
import requests # importing the request module

url = 'https://www.w3.org/TR/PNG/iso_8859-1.txt' # text from a website

response = requests.get(url) # opening a network and fetching a data
print(response)
print(response.status_code) # status code, success:200
print(response.headers)     # headers information
print(response.text) # gives all the text from the page

<Response [404]>
404
{'date': 'Sat, 29 Oct 2022 00:29:57 GMT', 'content-length': '6715', 'content-type': 'text/html;charset=utf-8', 'x-backend': 'ssl-mirrors', 'x-request-id': '635c7405651f0d7b', 'strict-transport-security': 'max-age=15552000; includeSubdomains; preload', 'content-security-policy': 'upgrade-insecure-requests'}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
  <title>Error 404 - Not found</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="Help" href="/Help/" />
  <link rel="stylesheet" href="/2008/site/css/minimum" type="text/css" media="all" />
  <style type="text/css"  media="print, screen and (min-width: 481px)">@import url("/2008/site/css/advanced");</style>
  <link href="/2008/site/css/minimum" rel="stylesheet" type="text/css" media="only screen and (max-width: 480px)" />
  <meta name=

In [14]:
# Let us read from an API. API stands for Application Program Interface. It is a means to exchange structure data between servers primarily a json data. 
# An example of an API:https://restcountries.eu/rest/v2/all. Let us read this API using requests module.

In [15]:
import requests
url = 'https://restcountries.eu/rest/v2/all'  # countries api
response = requests.get(url)  # opening a network and fetching a data
print(response) # response object
print(response.status_code)  # status code, success:200
countries = response.json()
print(countries[:1])  # we sliced only the first country, remove the slicing to see all countries

ConnectionError: HTTPSConnectionPool(host='restcountries.eu', port=443): Max retries exceeded with url: /rest/v2/all (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022DFC61F940>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

# Creating a Package
## We organize a large number of files in different folders and sub-folders based on some criteria, so that we can find and manage them easily. As you know, a module can contain multiple objects, such as classes, functions, etc. A package can contain one or more relevant modules. A package is actually a folder containing one or more module files. Let us create a package named mypackage, using the following steps:

# The folder structure of your package should look like this:

### ─ mypackage
###    ├── __init__.py
###    ├── arithmetics.py
###    └── greet.py

In [18]:
from my_package import arithmetics

arithmetics.add_numbers(1,2,3,4,5,6)

21

In [17]:
arithmetics.power(5,3)

125

In [19]:
# As you can see our package works perfectly. The package folder contains a special file called init.py - it stores the package's content.
#  If we put init.py in the package folder, python start recognizes it as a package.
#  The init.py exposes specified resources from its modules to be imported to other python files. 
# An empty init.py file makes all functions available when a package is imported. 
# The init.py is essential for the folder to be recognized by Python as a package.